/*
Clover API

Testing PostgresMetricDestinationApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/mohi-kalantari/ubicloud-go-client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_PostgresMetricDestinationApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PostgresMetricDestinationApiService CreateLocationPostgresMetricDestination", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var location string
		var postgresDatabaseName string
		var projectId string

		resp, httpRes, err := apiClient.PostgresMetricDestinationApi.CreateLocationPostgresMetricDestination(context.Background(), location, postgresDatabaseName, projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PostgresMetricDestinationApiService DeleteLocationPostgresMetricDestination", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var location string
		var metricDestinationId string
		var postgresDatabaseName string
		var projectId string

		httpRes, err := apiClient.PostgresMetricDestinationApi.DeleteLocationPostgresMetricDestination(context.Background(), location, metricDestinationId, postgresDatabaseName, projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
