/*
Clover API

Testing KubernetesVMApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/mohi-kalantari/ubicloud-go-client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_KubernetesVMApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KubernetesVMApiService CreateLocationKubernetesVM", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectId string
		var location string
		var kubernetesVmName string

		resp, httpRes, err := apiClient.KubernetesVMApi.CreateLocationKubernetesVM(context.Background(), projectId, location, kubernetesVmName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
