/*
Clover API

Testing KubernetesClusterApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/mohi-kalantari/ubicloud-go-client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_KubernetesClusterApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KubernetesClusterApiService CreateLocationKubernetesCluster", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectId string
		var location string
		var kubernetesClusterName string

		resp, httpRes, err := apiClient.KubernetesClusterApi.CreateLocationKubernetesCluster(context.Background(), projectId, location, kubernetesClusterName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KubernetesClusterApiService ListLocationKubernetesClusters", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var projectId string
		var location string

		resp, httpRes, err := apiClient.KubernetesClusterApi.ListLocationKubernetesClusters(context.Background(), projectId, location).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
