/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListLocationKubernetesVMs200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLocationKubernetesVMs200Response{}

// ListLocationKubernetesVMs200Response struct for ListLocationKubernetesVMs200Response
type ListLocationKubernetesVMs200Response struct {
	Count int32 `json:"count"`
	Items []VmDetailed `json:"items"`
}

// NewListLocationKubernetesVMs200Response instantiates a new ListLocationKubernetesVMs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLocationKubernetesVMs200Response(count int32, items []VmDetailed) *ListLocationKubernetesVMs200Response {
	this := ListLocationKubernetesVMs200Response{}
	this.Count = count
	this.Items = items
	return &this
}

// NewListLocationKubernetesVMs200ResponseWithDefaults instantiates a new ListLocationKubernetesVMs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLocationKubernetesVMs200ResponseWithDefaults() *ListLocationKubernetesVMs200Response {
	this := ListLocationKubernetesVMs200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *ListLocationKubernetesVMs200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ListLocationKubernetesVMs200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ListLocationKubernetesVMs200Response) SetCount(v int32) {
	o.Count = v
}

// GetItems returns the Items field value
func (o *ListLocationKubernetesVMs200Response) GetItems() []VmDetailed {
	if o == nil {
		var ret []VmDetailed
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListLocationKubernetesVMs200Response) GetItemsOk() ([]VmDetailed, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListLocationKubernetesVMs200Response) SetItems(v []VmDetailed) {
	o.Items = v
}

func (o ListLocationKubernetesVMs200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLocationKubernetesVMs200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListLocationKubernetesVMs200Response struct {
	value *ListLocationKubernetesVMs200Response
	isSet bool
}

func (v NullableListLocationKubernetesVMs200Response) Get() *ListLocationKubernetesVMs200Response {
	return v.value
}

func (v *NullableListLocationKubernetesVMs200Response) Set(val *ListLocationKubernetesVMs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLocationKubernetesVMs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLocationKubernetesVMs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLocationKubernetesVMs200Response(val *ListLocationKubernetesVMs200Response) *NullableListLocationKubernetesVMs200Response {
	return &NullableListLocationKubernetesVMs200Response{value: val, isSet: true}
}

func (v NullableListLocationKubernetesVMs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLocationKubernetesVMs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


