/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListProjects200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProjects200Response{}

// ListProjects200Response struct for ListProjects200Response
type ListProjects200Response struct {
	Count int32 `json:"count"`
	Items []Project `json:"items"`
}

// NewListProjects200Response instantiates a new ListProjects200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProjects200Response(count int32, items []Project) *ListProjects200Response {
	this := ListProjects200Response{}
	this.Count = count
	this.Items = items
	return &this
}

// NewListProjects200ResponseWithDefaults instantiates a new ListProjects200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProjects200ResponseWithDefaults() *ListProjects200Response {
	this := ListProjects200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *ListProjects200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ListProjects200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ListProjects200Response) SetCount(v int32) {
	o.Count = v
}

// GetItems returns the Items field value
func (o *ListProjects200Response) GetItems() []Project {
	if o == nil {
		var ret []Project
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListProjects200Response) GetItemsOk() ([]Project, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListProjects200Response) SetItems(v []Project) {
	o.Items = v
}

func (o ListProjects200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProjects200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListProjects200Response struct {
	value *ListProjects200Response
	isSet bool
}

func (v NullableListProjects200Response) Get() *ListProjects200Response {
	return v.value
}

func (v *NullableListProjects200Response) Set(val *ListProjects200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListProjects200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListProjects200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProjects200Response(val *ListProjects200Response) *NullableListProjects200Response {
	return &NullableListProjects200Response{value: val, isSet: true}
}

func (v NullableListProjects200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProjects200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


