/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ActionLocationFirewallAttachSubnetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionLocationFirewallAttachSubnetRequest{}

// ActionLocationFirewallAttachSubnetRequest struct for ActionLocationFirewallAttachSubnetRequest
type ActionLocationFirewallAttachSubnetRequest struct {
	// Private subnet id to attach
	PrivateSubnetId string `json:"private_subnet_id"`
}

// NewActionLocationFirewallAttachSubnetRequest instantiates a new ActionLocationFirewallAttachSubnetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionLocationFirewallAttachSubnetRequest(privateSubnetId string) *ActionLocationFirewallAttachSubnetRequest {
	this := ActionLocationFirewallAttachSubnetRequest{}
	this.PrivateSubnetId = privateSubnetId
	return &this
}

// NewActionLocationFirewallAttachSubnetRequestWithDefaults instantiates a new ActionLocationFirewallAttachSubnetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionLocationFirewallAttachSubnetRequestWithDefaults() *ActionLocationFirewallAttachSubnetRequest {
	this := ActionLocationFirewallAttachSubnetRequest{}
	return &this
}

// GetPrivateSubnetId returns the PrivateSubnetId field value
func (o *ActionLocationFirewallAttachSubnetRequest) GetPrivateSubnetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrivateSubnetId
}

// GetPrivateSubnetIdOk returns a tuple with the PrivateSubnetId field value
// and a boolean to check if the value has been set.
func (o *ActionLocationFirewallAttachSubnetRequest) GetPrivateSubnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrivateSubnetId, true
}

// SetPrivateSubnetId sets field value
func (o *ActionLocationFirewallAttachSubnetRequest) SetPrivateSubnetId(v string) {
	o.PrivateSubnetId = v
}

func (o ActionLocationFirewallAttachSubnetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionLocationFirewallAttachSubnetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["private_subnet_id"] = o.PrivateSubnetId
	return toSerialize, nil
}

type NullableActionLocationFirewallAttachSubnetRequest struct {
	value *ActionLocationFirewallAttachSubnetRequest
	isSet bool
}

func (v NullableActionLocationFirewallAttachSubnetRequest) Get() *ActionLocationFirewallAttachSubnetRequest {
	return v.value
}

func (v *NullableActionLocationFirewallAttachSubnetRequest) Set(val *ActionLocationFirewallAttachSubnetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableActionLocationFirewallAttachSubnetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableActionLocationFirewallAttachSubnetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionLocationFirewallAttachSubnetRequest(val *ActionLocationFirewallAttachSubnetRequest) *NullableActionLocationFirewallAttachSubnetRequest {
	return &NullableActionLocationFirewallAttachSubnetRequest{value: val, isSet: true}
}

func (v NullableActionLocationFirewallAttachSubnetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionLocationFirewallAttachSubnetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


