/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListLocationVMs200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLocationVMs200Response{}

// ListLocationVMs200Response struct for ListLocationVMs200Response
type ListLocationVMs200Response struct {
	Count int32 `json:"count"`
	Items []Vm `json:"items"`
}

// NewListLocationVMs200Response instantiates a new ListLocationVMs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLocationVMs200Response(count int32, items []Vm) *ListLocationVMs200Response {
	this := ListLocationVMs200Response{}
	this.Count = count
	this.Items = items
	return &this
}

// NewListLocationVMs200ResponseWithDefaults instantiates a new ListLocationVMs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLocationVMs200ResponseWithDefaults() *ListLocationVMs200Response {
	this := ListLocationVMs200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *ListLocationVMs200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ListLocationVMs200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ListLocationVMs200Response) SetCount(v int32) {
	o.Count = v
}

// GetItems returns the Items field value
func (o *ListLocationVMs200Response) GetItems() []Vm {
	if o == nil {
		var ret []Vm
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListLocationVMs200Response) GetItemsOk() ([]Vm, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListLocationVMs200Response) SetItems(v []Vm) {
	o.Items = v
}

func (o ListLocationVMs200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLocationVMs200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListLocationVMs200Response struct {
	value *ListLocationVMs200Response
	isSet bool
}

func (v NullableListLocationVMs200Response) Get() *ListLocationVMs200Response {
	return v.value
}

func (v *NullableListLocationVMs200Response) Set(val *ListLocationVMs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLocationVMs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLocationVMs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLocationVMs200Response(val *ListLocationVMs200Response) *NullableListLocationVMs200Response {
	return &NullableListLocationVMs200Response{value: val, isSet: true}
}

func (v NullableListLocationVMs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLocationVMs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


