/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateLocationKubernetesVMRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLocationKubernetesVMRequest{}

// CreateLocationKubernetesVMRequest struct for CreateLocationKubernetesVMRequest
type CreateLocationKubernetesVMRequest struct {
	// Boot image of the VM
	BootImage string `json:"boot_image"`
	// Enable IPv4
	EnableIp4 bool `json:"enable_ip4"`
	// ID of the private subnet
	PrivateSubnetId string `json:"private_subnet_id"`
	// Size of the VM
	Size string `json:"size"`
	// Requested storage size in GiB
	StorageSize int32 `json:"storage_size"`
	// Unix user of the VM
	UnixUser string `json:"unix_user"`
	// List of commands for the Kubernetes VM
	Commands []string `json:"commands"`
}

// NewCreateLocationKubernetesVMRequest instantiates a new CreateLocationKubernetesVMRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLocationKubernetesVMRequest(bootImage string, enableIp4 bool, privateSubnetId string, size string, storageSize int32, unixUser string, commands []string) *CreateLocationKubernetesVMRequest {
	this := CreateLocationKubernetesVMRequest{}
	this.BootImage = bootImage
	this.EnableIp4 = enableIp4
	this.PrivateSubnetId = privateSubnetId
	this.Size = size
	this.StorageSize = storageSize
	this.UnixUser = unixUser
	this.Commands = commands
	return &this
}

// NewCreateLocationKubernetesVMRequestWithDefaults instantiates a new CreateLocationKubernetesVMRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLocationKubernetesVMRequestWithDefaults() *CreateLocationKubernetesVMRequest {
	this := CreateLocationKubernetesVMRequest{}
	return &this
}

// GetBootImage returns the BootImage field value
func (o *CreateLocationKubernetesVMRequest) GetBootImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BootImage
}

// GetBootImageOk returns a tuple with the BootImage field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesVMRequest) GetBootImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BootImage, true
}

// SetBootImage sets field value
func (o *CreateLocationKubernetesVMRequest) SetBootImage(v string) {
	o.BootImage = v
}

// GetEnableIp4 returns the EnableIp4 field value
func (o *CreateLocationKubernetesVMRequest) GetEnableIp4() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EnableIp4
}

// GetEnableIp4Ok returns a tuple with the EnableIp4 field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesVMRequest) GetEnableIp4Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnableIp4, true
}

// SetEnableIp4 sets field value
func (o *CreateLocationKubernetesVMRequest) SetEnableIp4(v bool) {
	o.EnableIp4 = v
}

// GetPrivateSubnetId returns the PrivateSubnetId field value
func (o *CreateLocationKubernetesVMRequest) GetPrivateSubnetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrivateSubnetId
}

// GetPrivateSubnetIdOk returns a tuple with the PrivateSubnetId field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesVMRequest) GetPrivateSubnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrivateSubnetId, true
}

// SetPrivateSubnetId sets field value
func (o *CreateLocationKubernetesVMRequest) SetPrivateSubnetId(v string) {
	o.PrivateSubnetId = v
}

// GetSize returns the Size field value
func (o *CreateLocationKubernetesVMRequest) GetSize() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesVMRequest) GetSizeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *CreateLocationKubernetesVMRequest) SetSize(v string) {
	o.Size = v
}

// GetStorageSize returns the StorageSize field value
func (o *CreateLocationKubernetesVMRequest) GetStorageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StorageSize
}

// GetStorageSizeOk returns a tuple with the StorageSize field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesVMRequest) GetStorageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageSize, true
}

// SetStorageSize sets field value
func (o *CreateLocationKubernetesVMRequest) SetStorageSize(v int32) {
	o.StorageSize = v
}

// GetUnixUser returns the UnixUser field value
func (o *CreateLocationKubernetesVMRequest) GetUnixUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UnixUser
}

// GetUnixUserOk returns a tuple with the UnixUser field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesVMRequest) GetUnixUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnixUser, true
}

// SetUnixUser sets field value
func (o *CreateLocationKubernetesVMRequest) SetUnixUser(v string) {
	o.UnixUser = v
}

// GetCommands returns the Commands field value
func (o *CreateLocationKubernetesVMRequest) GetCommands() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Commands
}

// GetCommandsOk returns a tuple with the Commands field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesVMRequest) GetCommandsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Commands, true
}

// SetCommands sets field value
func (o *CreateLocationKubernetesVMRequest) SetCommands(v []string) {
	o.Commands = v
}

func (o CreateLocationKubernetesVMRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLocationKubernetesVMRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["boot_image"] = o.BootImage
	toSerialize["enable_ip4"] = o.EnableIp4
	toSerialize["private_subnet_id"] = o.PrivateSubnetId
	toSerialize["size"] = o.Size
	toSerialize["storage_size"] = o.StorageSize
	toSerialize["unix_user"] = o.UnixUser
	toSerialize["commands"] = o.Commands
	return toSerialize, nil
}

type NullableCreateLocationKubernetesVMRequest struct {
	value *CreateLocationKubernetesVMRequest
	isSet bool
}

func (v NullableCreateLocationKubernetesVMRequest) Get() *CreateLocationKubernetesVMRequest {
	return v.value
}

func (v *NullableCreateLocationKubernetesVMRequest) Set(val *CreateLocationKubernetesVMRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLocationKubernetesVMRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLocationKubernetesVMRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLocationKubernetesVMRequest(val *CreateLocationKubernetesVMRequest) *NullableCreateLocationKubernetesVMRequest {
	return &NullableCreateLocationKubernetesVMRequest{value: val, isSet: true}
}

func (v NullableCreateLocationKubernetesVMRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLocationKubernetesVMRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


