/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateFirewallRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFirewallRequest{}

// CreateFirewallRequest struct for CreateFirewallRequest
type CreateFirewallRequest struct {
	// Description of the firewall
	Description *string `json:"description,omitempty"`
	// Name of the firewall
	Name string `json:"name"`
}

// NewCreateFirewallRequest instantiates a new CreateFirewallRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFirewallRequest(name string) *CreateFirewallRequest {
	this := CreateFirewallRequest{}
	this.Name = name
	return &this
}

// NewCreateFirewallRequestWithDefaults instantiates a new CreateFirewallRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFirewallRequestWithDefaults() *CreateFirewallRequest {
	this := CreateFirewallRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateFirewallRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFirewallRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateFirewallRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateFirewallRequest) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *CreateFirewallRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateFirewallRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateFirewallRequest) SetName(v string) {
	o.Name = v
}

func (o CreateFirewallRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFirewallRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableCreateFirewallRequest struct {
	value *CreateFirewallRequest
	isSet bool
}

func (v NullableCreateFirewallRequest) Get() *CreateFirewallRequest {
	return v.value
}

func (v *NullableCreateFirewallRequest) Set(val *CreateFirewallRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFirewallRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFirewallRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFirewallRequest(val *CreateFirewallRequest) *NullableCreateFirewallRequest {
	return &NullableCreateFirewallRequest{value: val, isSet: true}
}

func (v NullableCreateFirewallRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFirewallRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


