/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListLocationPostgresFirewallRules200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLocationPostgresFirewallRules200Response{}

// ListLocationPostgresFirewallRules200Response struct for ListLocationPostgresFirewallRules200Response
type ListLocationPostgresFirewallRules200Response struct {
	Count int32 `json:"count"`
	Items []PostgresFirewallRule `json:"items"`
}

// NewListLocationPostgresFirewallRules200Response instantiates a new ListLocationPostgresFirewallRules200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLocationPostgresFirewallRules200Response(count int32, items []PostgresFirewallRule) *ListLocationPostgresFirewallRules200Response {
	this := ListLocationPostgresFirewallRules200Response{}
	this.Count = count
	this.Items = items
	return &this
}

// NewListLocationPostgresFirewallRules200ResponseWithDefaults instantiates a new ListLocationPostgresFirewallRules200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLocationPostgresFirewallRules200ResponseWithDefaults() *ListLocationPostgresFirewallRules200Response {
	this := ListLocationPostgresFirewallRules200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *ListLocationPostgresFirewallRules200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ListLocationPostgresFirewallRules200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ListLocationPostgresFirewallRules200Response) SetCount(v int32) {
	o.Count = v
}

// GetItems returns the Items field value
func (o *ListLocationPostgresFirewallRules200Response) GetItems() []PostgresFirewallRule {
	if o == nil {
		var ret []PostgresFirewallRule
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListLocationPostgresFirewallRules200Response) GetItemsOk() ([]PostgresFirewallRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListLocationPostgresFirewallRules200Response) SetItems(v []PostgresFirewallRule) {
	o.Items = v
}

func (o ListLocationPostgresFirewallRules200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLocationPostgresFirewallRules200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListLocationPostgresFirewallRules200Response struct {
	value *ListLocationPostgresFirewallRules200Response
	isSet bool
}

func (v NullableListLocationPostgresFirewallRules200Response) Get() *ListLocationPostgresFirewallRules200Response {
	return v.value
}

func (v *NullableListLocationPostgresFirewallRules200Response) Set(val *ListLocationPostgresFirewallRules200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLocationPostgresFirewallRules200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLocationPostgresFirewallRules200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLocationPostgresFirewallRules200Response(val *ListLocationPostgresFirewallRules200Response) *NullableListLocationPostgresFirewallRules200Response {
	return &NullableListLocationPostgresFirewallRules200Response{value: val, isSet: true}
}

func (v NullableListLocationPostgresFirewallRules200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLocationPostgresFirewallRules200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


