/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateLocationPostgresMetricDestinationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLocationPostgresMetricDestinationRequest{}

// CreateLocationPostgresMetricDestinationRequest struct for CreateLocationPostgresMetricDestinationRequest
type CreateLocationPostgresMetricDestinationRequest struct {
	// Password for the Metric Destination
	Password string `json:"password"`
	// URL for the Metric Destination
	Url string `json:"url"`
	// Username for the Metric Destination
	Username string `json:"username"`
}

// NewCreateLocationPostgresMetricDestinationRequest instantiates a new CreateLocationPostgresMetricDestinationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLocationPostgresMetricDestinationRequest(password string, url string, username string) *CreateLocationPostgresMetricDestinationRequest {
	this := CreateLocationPostgresMetricDestinationRequest{}
	this.Password = password
	this.Url = url
	this.Username = username
	return &this
}

// NewCreateLocationPostgresMetricDestinationRequestWithDefaults instantiates a new CreateLocationPostgresMetricDestinationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLocationPostgresMetricDestinationRequestWithDefaults() *CreateLocationPostgresMetricDestinationRequest {
	this := CreateLocationPostgresMetricDestinationRequest{}
	return &this
}

// GetPassword returns the Password field value
func (o *CreateLocationPostgresMetricDestinationRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CreateLocationPostgresMetricDestinationRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CreateLocationPostgresMetricDestinationRequest) SetPassword(v string) {
	o.Password = v
}

// GetUrl returns the Url field value
func (o *CreateLocationPostgresMetricDestinationRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateLocationPostgresMetricDestinationRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateLocationPostgresMetricDestinationRequest) SetUrl(v string) {
	o.Url = v
}

// GetUsername returns the Username field value
func (o *CreateLocationPostgresMetricDestinationRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *CreateLocationPostgresMetricDestinationRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *CreateLocationPostgresMetricDestinationRequest) SetUsername(v string) {
	o.Username = v
}

func (o CreateLocationPostgresMetricDestinationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLocationPostgresMetricDestinationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	toSerialize["url"] = o.Url
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

type NullableCreateLocationPostgresMetricDestinationRequest struct {
	value *CreateLocationPostgresMetricDestinationRequest
	isSet bool
}

func (v NullableCreateLocationPostgresMetricDestinationRequest) Get() *CreateLocationPostgresMetricDestinationRequest {
	return v.value
}

func (v *NullableCreateLocationPostgresMetricDestinationRequest) Set(val *CreateLocationPostgresMetricDestinationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLocationPostgresMetricDestinationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLocationPostgresMetricDestinationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLocationPostgresMetricDestinationRequest(val *CreateLocationPostgresMetricDestinationRequest) *NullableCreateLocationPostgresMetricDestinationRequest {
	return &NullableCreateLocationPostgresMetricDestinationRequest{value: val, isSet: true}
}

func (v NullableCreateLocationPostgresMetricDestinationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLocationPostgresMetricDestinationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


