/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreatePrivateSubnetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePrivateSubnetRequest{}

// CreatePrivateSubnetRequest struct for CreatePrivateSubnetRequest
type CreatePrivateSubnetRequest struct {
	FirewallId *string `json:"firewall_id,omitempty"`
}

// NewCreatePrivateSubnetRequest instantiates a new CreatePrivateSubnetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePrivateSubnetRequest() *CreatePrivateSubnetRequest {
	this := CreatePrivateSubnetRequest{}
	return &this
}

// NewCreatePrivateSubnetRequestWithDefaults instantiates a new CreatePrivateSubnetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePrivateSubnetRequestWithDefaults() *CreatePrivateSubnetRequest {
	this := CreatePrivateSubnetRequest{}
	return &this
}

// GetFirewallId returns the FirewallId field value if set, zero value otherwise.
func (o *CreatePrivateSubnetRequest) GetFirewallId() string {
	if o == nil || IsNil(o.FirewallId) {
		var ret string
		return ret
	}
	return *o.FirewallId
}

// GetFirewallIdOk returns a tuple with the FirewallId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrivateSubnetRequest) GetFirewallIdOk() (*string, bool) {
	if o == nil || IsNil(o.FirewallId) {
		return nil, false
	}
	return o.FirewallId, true
}

// HasFirewallId returns a boolean if a field has been set.
func (o *CreatePrivateSubnetRequest) HasFirewallId() bool {
	if o != nil && !IsNil(o.FirewallId) {
		return true
	}

	return false
}

// SetFirewallId gets a reference to the given string and assigns it to the FirewallId field.
func (o *CreatePrivateSubnetRequest) SetFirewallId(v string) {
	o.FirewallId = &v
}

func (o CreatePrivateSubnetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePrivateSubnetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirewallId) {
		toSerialize["firewall_id"] = o.FirewallId
	}
	return toSerialize, nil
}

type NullableCreatePrivateSubnetRequest struct {
	value *CreatePrivateSubnetRequest
	isSet bool
}

func (v NullableCreatePrivateSubnetRequest) Get() *CreatePrivateSubnetRequest {
	return v.value
}

func (v *NullableCreatePrivateSubnetRequest) Set(val *CreatePrivateSubnetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePrivateSubnetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePrivateSubnetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePrivateSubnetRequest(val *CreatePrivateSubnetRequest) *NullableCreatePrivateSubnetRequest {
	return &NullableCreatePrivateSubnetRequest{value: val, isSet: true}
}

func (v NullableCreatePrivateSubnetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePrivateSubnetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


