/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListLoadBalancers200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLoadBalancers200Response{}

// ListLoadBalancers200Response struct for ListLoadBalancers200Response
type ListLoadBalancers200Response struct {
	Count int32 `json:"count"`
	Items []LoadBalancer `json:"items"`
}

// NewListLoadBalancers200Response instantiates a new ListLoadBalancers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLoadBalancers200Response(count int32, items []LoadBalancer) *ListLoadBalancers200Response {
	this := ListLoadBalancers200Response{}
	this.Count = count
	this.Items = items
	return &this
}

// NewListLoadBalancers200ResponseWithDefaults instantiates a new ListLoadBalancers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLoadBalancers200ResponseWithDefaults() *ListLoadBalancers200Response {
	this := ListLoadBalancers200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *ListLoadBalancers200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ListLoadBalancers200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ListLoadBalancers200Response) SetCount(v int32) {
	o.Count = v
}

// GetItems returns the Items field value
func (o *ListLoadBalancers200Response) GetItems() []LoadBalancer {
	if o == nil {
		var ret []LoadBalancer
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListLoadBalancers200Response) GetItemsOk() ([]LoadBalancer, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListLoadBalancers200Response) SetItems(v []LoadBalancer) {
	o.Items = v
}

func (o ListLoadBalancers200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLoadBalancers200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListLoadBalancers200Response struct {
	value *ListLoadBalancers200Response
	isSet bool
}

func (v NullableListLoadBalancers200Response) Get() *ListLoadBalancers200Response {
	return v.value
}

func (v *NullableListLoadBalancers200Response) Set(val *ListLoadBalancers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLoadBalancers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLoadBalancers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLoadBalancers200Response(val *ListLoadBalancers200Response) *NullableListLoadBalancers200Response {
	return &NullableListLoadBalancers200Response{value: val, isSet: true}
}

func (v NullableListLoadBalancers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLoadBalancers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


