/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ActionLocationFirewallDetachSubnetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionLocationFirewallDetachSubnetRequest{}

// ActionLocationFirewallDetachSubnetRequest struct for ActionLocationFirewallDetachSubnetRequest
type ActionLocationFirewallDetachSubnetRequest struct {
	// Private subnet id to detach
	PrivateSubnetId string `json:"private_subnet_id"`
}

// NewActionLocationFirewallDetachSubnetRequest instantiates a new ActionLocationFirewallDetachSubnetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionLocationFirewallDetachSubnetRequest(privateSubnetId string) *ActionLocationFirewallDetachSubnetRequest {
	this := ActionLocationFirewallDetachSubnetRequest{}
	this.PrivateSubnetId = privateSubnetId
	return &this
}

// NewActionLocationFirewallDetachSubnetRequestWithDefaults instantiates a new ActionLocationFirewallDetachSubnetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionLocationFirewallDetachSubnetRequestWithDefaults() *ActionLocationFirewallDetachSubnetRequest {
	this := ActionLocationFirewallDetachSubnetRequest{}
	return &this
}

// GetPrivateSubnetId returns the PrivateSubnetId field value
func (o *ActionLocationFirewallDetachSubnetRequest) GetPrivateSubnetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrivateSubnetId
}

// GetPrivateSubnetIdOk returns a tuple with the PrivateSubnetId field value
// and a boolean to check if the value has been set.
func (o *ActionLocationFirewallDetachSubnetRequest) GetPrivateSubnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrivateSubnetId, true
}

// SetPrivateSubnetId sets field value
func (o *ActionLocationFirewallDetachSubnetRequest) SetPrivateSubnetId(v string) {
	o.PrivateSubnetId = v
}

func (o ActionLocationFirewallDetachSubnetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionLocationFirewallDetachSubnetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["private_subnet_id"] = o.PrivateSubnetId
	return toSerialize, nil
}

type NullableActionLocationFirewallDetachSubnetRequest struct {
	value *ActionLocationFirewallDetachSubnetRequest
	isSet bool
}

func (v NullableActionLocationFirewallDetachSubnetRequest) Get() *ActionLocationFirewallDetachSubnetRequest {
	return v.value
}

func (v *NullableActionLocationFirewallDetachSubnetRequest) Set(val *ActionLocationFirewallDetachSubnetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableActionLocationFirewallDetachSubnetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableActionLocationFirewallDetachSubnetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionLocationFirewallDetachSubnetRequest(val *ActionLocationFirewallDetachSubnetRequest) *NullableActionLocationFirewallDetachSubnetRequest {
	return &NullableActionLocationFirewallDetachSubnetRequest{value: val, isSet: true}
}

func (v NullableActionLocationFirewallDetachSubnetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionLocationFirewallDetachSubnetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


