/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateLocationFirewallRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLocationFirewallRequest{}

// CreateLocationFirewallRequest struct for CreateLocationFirewallRequest
type CreateLocationFirewallRequest struct {
	// Description of the firewall
	Description *string `json:"description,omitempty"`
}

// NewCreateLocationFirewallRequest instantiates a new CreateLocationFirewallRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLocationFirewallRequest() *CreateLocationFirewallRequest {
	this := CreateLocationFirewallRequest{}
	return &this
}

// NewCreateLocationFirewallRequestWithDefaults instantiates a new CreateLocationFirewallRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLocationFirewallRequestWithDefaults() *CreateLocationFirewallRequest {
	this := CreateLocationFirewallRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateLocationFirewallRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLocationFirewallRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateLocationFirewallRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateLocationFirewallRequest) SetDescription(v string) {
	o.Description = &v
}

func (o CreateLocationFirewallRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLocationFirewallRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableCreateLocationFirewallRequest struct {
	value *CreateLocationFirewallRequest
	isSet bool
}

func (v NullableCreateLocationFirewallRequest) Get() *CreateLocationFirewallRequest {
	return v.value
}

func (v *NullableCreateLocationFirewallRequest) Set(val *CreateLocationFirewallRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLocationFirewallRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLocationFirewallRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLocationFirewallRequest(val *CreateLocationFirewallRequest) *NullableCreateLocationFirewallRequest {
	return &NullableCreateLocationFirewallRequest{value: val, isSet: true}
}

func (v NullableCreateLocationFirewallRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLocationFirewallRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


