/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetKubernetesCluster200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetKubernetesCluster200Response{}

// GetKubernetesCluster200Response struct for GetKubernetesCluster200Response
type GetKubernetesCluster200Response struct {
	Count int32 `json:"count"`
	Items []KubernetesCluster `json:"items"`
}

// NewGetKubernetesCluster200Response instantiates a new GetKubernetesCluster200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetKubernetesCluster200Response(count int32, items []KubernetesCluster) *GetKubernetesCluster200Response {
	this := GetKubernetesCluster200Response{}
	this.Count = count
	this.Items = items
	return &this
}

// NewGetKubernetesCluster200ResponseWithDefaults instantiates a new GetKubernetesCluster200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetKubernetesCluster200ResponseWithDefaults() *GetKubernetesCluster200Response {
	this := GetKubernetesCluster200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *GetKubernetesCluster200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *GetKubernetesCluster200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *GetKubernetesCluster200Response) SetCount(v int32) {
	o.Count = v
}

// GetItems returns the Items field value
func (o *GetKubernetesCluster200Response) GetItems() []KubernetesCluster {
	if o == nil {
		var ret []KubernetesCluster
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *GetKubernetesCluster200Response) GetItemsOk() ([]KubernetesCluster, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *GetKubernetesCluster200Response) SetItems(v []KubernetesCluster) {
	o.Items = v
}

func (o GetKubernetesCluster200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetKubernetesCluster200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableGetKubernetesCluster200Response struct {
	value *GetKubernetesCluster200Response
	isSet bool
}

func (v NullableGetKubernetesCluster200Response) Get() *GetKubernetesCluster200Response {
	return v.value
}

func (v *NullableGetKubernetesCluster200Response) Set(val *GetKubernetesCluster200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetKubernetesCluster200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetKubernetesCluster200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetKubernetesCluster200Response(val *GetKubernetesCluster200Response) *NullableGetKubernetesCluster200Response {
	return &NullableGetKubernetesCluster200Response{value: val, isSet: true}
}

func (v NullableGetKubernetesCluster200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetKubernetesCluster200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


