/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListLocationPostgresDatabases200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLocationPostgresDatabases200Response{}

// ListLocationPostgresDatabases200Response struct for ListLocationPostgresDatabases200Response
type ListLocationPostgresDatabases200Response struct {
	Count int32 `json:"count"`
	Items []Postgres `json:"items"`
}

// NewListLocationPostgresDatabases200Response instantiates a new ListLocationPostgresDatabases200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLocationPostgresDatabases200Response(count int32, items []Postgres) *ListLocationPostgresDatabases200Response {
	this := ListLocationPostgresDatabases200Response{}
	this.Count = count
	this.Items = items
	return &this
}

// NewListLocationPostgresDatabases200ResponseWithDefaults instantiates a new ListLocationPostgresDatabases200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLocationPostgresDatabases200ResponseWithDefaults() *ListLocationPostgresDatabases200Response {
	this := ListLocationPostgresDatabases200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *ListLocationPostgresDatabases200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ListLocationPostgresDatabases200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ListLocationPostgresDatabases200Response) SetCount(v int32) {
	o.Count = v
}

// GetItems returns the Items field value
func (o *ListLocationPostgresDatabases200Response) GetItems() []Postgres {
	if o == nil {
		var ret []Postgres
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListLocationPostgresDatabases200Response) GetItemsOk() ([]Postgres, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListLocationPostgresDatabases200Response) SetItems(v []Postgres) {
	o.Items = v
}

func (o ListLocationPostgresDatabases200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLocationPostgresDatabases200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListLocationPostgresDatabases200Response struct {
	value *ListLocationPostgresDatabases200Response
	isSet bool
}

func (v NullableListLocationPostgresDatabases200Response) Get() *ListLocationPostgresDatabases200Response {
	return v.value
}

func (v *NullableListLocationPostgresDatabases200Response) Set(val *ListLocationPostgresDatabases200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLocationPostgresDatabases200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLocationPostgresDatabases200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLocationPostgresDatabases200Response(val *ListLocationPostgresDatabases200Response) *NullableListLocationPostgresDatabases200Response {
	return &NullableListLocationPostgresDatabases200Response{value: val, isSet: true}
}

func (v NullableListLocationPostgresDatabases200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLocationPostgresDatabases200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


