/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateLocationKubernetesClusterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLocationKubernetesClusterRequest{}

// CreateLocationKubernetesClusterRequest struct for CreateLocationKubernetesClusterRequest
type CreateLocationKubernetesClusterRequest struct {
	// Name of subnet
	Subnet string `json:"subnet"`
	// Version of the kubernetes cluster
	KubernetesVersion string `json:"kubernetes_version"`
}

// NewCreateLocationKubernetesClusterRequest instantiates a new CreateLocationKubernetesClusterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLocationKubernetesClusterRequest(subnet string, kubernetesVersion string) *CreateLocationKubernetesClusterRequest {
	this := CreateLocationKubernetesClusterRequest{}
	this.Subnet = subnet
	this.KubernetesVersion = kubernetesVersion
	return &this
}

// NewCreateLocationKubernetesClusterRequestWithDefaults instantiates a new CreateLocationKubernetesClusterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLocationKubernetesClusterRequestWithDefaults() *CreateLocationKubernetesClusterRequest {
	this := CreateLocationKubernetesClusterRequest{}
	return &this
}

// GetSubnet returns the Subnet field value
func (o *CreateLocationKubernetesClusterRequest) GetSubnet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subnet
}

// GetSubnetOk returns a tuple with the Subnet field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesClusterRequest) GetSubnetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subnet, true
}

// SetSubnet sets field value
func (o *CreateLocationKubernetesClusterRequest) SetSubnet(v string) {
	o.Subnet = v
}

// GetKubernetesVersion returns the KubernetesVersion field value
func (o *CreateLocationKubernetesClusterRequest) GetKubernetesVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KubernetesVersion
}

// GetKubernetesVersionOk returns a tuple with the KubernetesVersion field value
// and a boolean to check if the value has been set.
func (o *CreateLocationKubernetesClusterRequest) GetKubernetesVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KubernetesVersion, true
}

// SetKubernetesVersion sets field value
func (o *CreateLocationKubernetesClusterRequest) SetKubernetesVersion(v string) {
	o.KubernetesVersion = v
}

func (o CreateLocationKubernetesClusterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLocationKubernetesClusterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subnet"] = o.Subnet
	toSerialize["kubernetes_version"] = o.KubernetesVersion
	return toSerialize, nil
}

type NullableCreateLocationKubernetesClusterRequest struct {
	value *CreateLocationKubernetesClusterRequest
	isSet bool
}

func (v NullableCreateLocationKubernetesClusterRequest) Get() *CreateLocationKubernetesClusterRequest {
	return v.value
}

func (v *NullableCreateLocationKubernetesClusterRequest) Set(val *CreateLocationKubernetesClusterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLocationKubernetesClusterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLocationKubernetesClusterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLocationKubernetesClusterRequest(val *CreateLocationKubernetesClusterRequest) *NullableCreateLocationKubernetesClusterRequest {
	return &NullableCreateLocationKubernetesClusterRequest{value: val, isSet: true}
}

func (v NullableCreateLocationKubernetesClusterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLocationKubernetesClusterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


