/*
Clover API

API for managing resources on Ubicloud

API version: 0.1.0
Contact: support@ubicloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListLocationPrivateSubnets200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListLocationPrivateSubnets200Response{}

// ListLocationPrivateSubnets200Response struct for ListLocationPrivateSubnets200Response
type ListLocationPrivateSubnets200Response struct {
	Count int32 `json:"count"`
	Items []PrivateSubnet `json:"items"`
}

// NewListLocationPrivateSubnets200Response instantiates a new ListLocationPrivateSubnets200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLocationPrivateSubnets200Response(count int32, items []PrivateSubnet) *ListLocationPrivateSubnets200Response {
	this := ListLocationPrivateSubnets200Response{}
	this.Count = count
	this.Items = items
	return &this
}

// NewListLocationPrivateSubnets200ResponseWithDefaults instantiates a new ListLocationPrivateSubnets200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLocationPrivateSubnets200ResponseWithDefaults() *ListLocationPrivateSubnets200Response {
	this := ListLocationPrivateSubnets200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *ListLocationPrivateSubnets200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ListLocationPrivateSubnets200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ListLocationPrivateSubnets200Response) SetCount(v int32) {
	o.Count = v
}

// GetItems returns the Items field value
func (o *ListLocationPrivateSubnets200Response) GetItems() []PrivateSubnet {
	if o == nil {
		var ret []PrivateSubnet
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListLocationPrivateSubnets200Response) GetItemsOk() ([]PrivateSubnet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListLocationPrivateSubnets200Response) SetItems(v []PrivateSubnet) {
	o.Items = v
}

func (o ListLocationPrivateSubnets200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListLocationPrivateSubnets200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListLocationPrivateSubnets200Response struct {
	value *ListLocationPrivateSubnets200Response
	isSet bool
}

func (v NullableListLocationPrivateSubnets200Response) Get() *ListLocationPrivateSubnets200Response {
	return v.value
}

func (v *NullableListLocationPrivateSubnets200Response) Set(val *ListLocationPrivateSubnets200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListLocationPrivateSubnets200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListLocationPrivateSubnets200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLocationPrivateSubnets200Response(val *ListLocationPrivateSubnets200Response) *NullableListLocationPrivateSubnets200Response {
	return &NullableListLocationPrivateSubnets200Response{value: val, isSet: true}
}

func (v NullableListLocationPrivateSubnets200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLocationPrivateSubnets200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


